### ISSUE TITLE
Broken sqlite

### ISSUE THREAD

**Issue by GamePanderDC** [TanteiBot/Tantei#616]
Hi. I am facing a problem with sqlite working when running the bot, can you help with this in any way?

```
[19.04.24 14\:23\:57.862 DBG] [PaperMalKing.Startup.Services.UpdatePublishingService]
Starting querying posting channels
[19.04.24 14\:23\:58.014 ERR] [Microsoft.EntityFrameworkCore.Database.Command]
Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
-- Query guild to save posting channels
-- File: /home/runner/work/Tantei/Tantei/src/PaperMalKing.Startup/Services/UpdatePublishingService.cs:53

SELECT "d"."DiscordGuildId", "d"."PostingChannelId"
FROM "DiscordGuilds" AS "d"
[19.04.24 14\:23\:58.023 ERR] [Microsoft.EntityFrameworkCore.Query]
An exception occurred while iterating over the results of a query for context type 'PaperMalKing.Database.DatabaseContext'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: DiscordGuilds'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: DiscordGuilds'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
[19.04.24 14\:23\:58.037 ERR] [PaperMalKing.Startup.Services.UpdatePublishingService]
Task on loading channels to post to failed
System.AggregateException: One or more errors occurred. (SQLite Error 1: 'no such table: DiscordGuilds'.)
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: DiscordGuilds'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at PaperMalKing.Startup.Services.UpdatePublishingService.<>c__DisplayClass7_0.<<DiscordClientOnGuildDownloadCompletedAsync>b__0>d.MoveNext() in /home/runner/work/Tantei/Tantei/src/PaperMalKing.Startup/Services/UpdatePublishingService.cs:line 53
--- End of stack trace from previous location ---
   at PaperMalKing.Startup.Services.UpdatePublishingService.<>c__DisplayClass7_0.<<DiscordClientOnGuildDownloadCompletedAsync>b__0>d.MoveNext() in /home/runner/work/Tantei/Tantei/src/PaperMalKing.Startup/Services/UpdatePublishingService.cs:line 80
   --- End of inner exception stack trace ---
      at PaperMalKing.Startup.Services.UpdatePublishingService.<>c__DisplayClass7_0.<<DiscordClientOnGuildDownloadCompletedAsync>b__0>d.MoveNext() in /home/runner/work/Tantei/Tantei/src/PaperMalKing.Startup/Services/UpdatePublishingService.cs:line 80
   --- End of inner exception stack trace ---
```

**Comment by N0D4N** [comment]
Fixed with [v2.7.3](https://github.com/TanteiBot/Tantei/releases/tag/v2.7.3) release.
Problem was with bot not creating DB structure that is expected for it to run. It was this way in the past, but for some reason i don't remember i changed the behaviour, to the one that caused issue for you.
Now it will apply all required changes on startup.
